### PR TITLE
Client#username_pw_access_token: raise error when username/password are blank

### PR DESCRIPTION
**Pull request by padi**
[#111746680]

https://pivotaltracker.com/story/show/111746680

### CODE REVIEW

**Comment by jmalvinchin** [comment]
:tea:

**Comment by riverblufftrail** [comment]
@maeve Someone how this missed your review.  Can you review this change ASAP and provide feedback

//cc @jpmoral @jmalvinchin

**Comment by maeve** [comment]
These changes look fine to me. Failing fast with a more descriptive error message is a good thing. However, I suspect this PR may not fix the `URI::BadURIError` described in the original issue (which is usually related to a missing value for the G5_AUTH_ENDPOINT, not a missing username or password).

**Comment by padi** [comment]
@maeve yes, I ended up forgetting about which particular env variable is causing the particular URI error G5_AUTH_ENDPOINT. Leaving issue #28 open then.

**Comment by riverblufftrail** [comment]
@padi should you revert your merge then until you fix that issue?

**Comment by padi** [comment]
@riverblufftrail the merge resolves the pivotaltracker story (having no G5_AUTH_USERNAME/PASSWORD set up results to errors), but I conflated the pivotal tracker story with the error concerning missing G5_AUTH_ENDPOINT (which should've been either a separate story, or properly included in the story title/description). Sorry for the confusion. I can quickly update the gem, rerelease it as another bugfix. We can wait for upgrading each app until the next gem release until then.

**Pull request merged**
